movies/urls.py
from django.urls import path 
from . import views


app_name = "movies"
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:movie_id>', views.detail, name = 'detail'),
]
 

video/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from .import views

movie_resourse = MovieResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resourse.urls))
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

# Create your models here.
class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created']
 

movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate =models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default = timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse ,Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    #output = ', '.join([m.title for m in movies])
    return render(request, 'movies/index.html', {'movies':movies})
    #return HttpResponse(output) 
    
def detail(request, movie_id):
    movie = get_object_or_404(Movie,pk=movie_id)
    return render(request, 'movies/detail.html',{'movie': movie})

video/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
    <dl>
        <dt>Title</dt>
        <dd>{{movie.title}}</dd>
        <dt>Genre</dt>
        <dd>{{movie.genre}}</dd>
        <dt>Stock</dt>
        <dd>{{movie.number_in_stock}}</dd>
    </dl>
{% endblock  %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Genre</th>
          <th scope="col">Stock</th>
          <th scope="col">Daily Rate</th>
        </tr>
      </thead>
      <tbody>
          {% for movie in movies %}
              <tr>
                <td>
                  <a href="{% url 'movies:detail' movie.id %}">{{ movie.title}}</a>
                  
                  
                  <td>{{movie.genre}}</td>
                  <td>{{movie.number_in_stock}}</td>
                  <td>{{movie.daily_rate}}</td>
              </tr>
        
          {% endfor %}
        
      </tbody>
    </table>

{% endblock  %}



 

templates/base.html
<!doctype html>
<html lang="en">
  <head>
  
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>video</title>
  </head>
  <body>

    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand">Videos</a>
        <form class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock  %}
    </main>  
    <footer>
    <p class="text-center bg-dark text-light fixed-bottom my-0 py-3">
    Made by pradeep
    </p>
    </footer>

  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<body style="background-color:gray;">

<div class = 'container my-3'>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
        <img src="https://source.unsplash.com/1900x700/?movies,marvel" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
        <img src="https://source.unsplash.com/1900x700/?villian,superman" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
        <img src="https://source.unsplash.com/1900x700/?superhero,django" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    </div>
</div>
<div class = 'container'>
    <p class = "text-center" style="font-size:50px;">Welcome!</p>
    <p> This site is to provide the list of movies and the Availability of those movies and the detailed informations about the movies you wish to view, To view the movies list --->Click the button below<--- </p>
    <h2 class = "text-center">    <a  href="{% url 'movies:index' %}"><button type="button" class="btn btn-primary btn-lg">Movies</button></a></h2>
   
</div>
    

{% endblock  %}